In [1]:
import tensorflow as tf

In [2]:
a = 1.2
aa = tf.constant(1.2) #创建标量
type(a),type(aa),tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [5]:
x = tf.constant([1,2.,3.3])
x
x.numpy()  #得到numpy.array类型的数据

array([1. , 2. , 3.3], dtype=float32)

向量的定义须通过list类型传给tf.constant()

In [6]:
a = tf.constant([1,2])
a,a.shape

(<tf.Tensor: id=8, shape=(2,), dtype=int32, numpy=array([1, 2])>,
 TensorShape([2]))

In [7]:
#定义矩阵
a = tf.constant([[1,2],[3,4.]])
a,a.shape

(<tf.Tensor: id=10, shape=(2, 2), dtype=float32, numpy=
 array([[1., 2.],
        [3., 4.]], dtype=float32)>, TensorShape([2, 2]))

In [8]:
#3维张量
a = tf.constant([[[1,2],[3,4],[5,6]]]) 
a,a.shape

(<tf.Tensor: id=12, shape=(1, 3, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4],
         [5, 6]]])>, TensorShape([1, 3, 2]))

# 字符串类型

In [10]:
a = tf.constant('Hello,NLP')
a

<tf.Tensor: id=15, shape=(), dtype=string, numpy=b'Hello,NLP'>

# tf.strings中提供常见的字符串类型工具函数，如join(),length()

In [14]:
print(tf.strings.length(a))

tf.Tensor(9, shape=(), dtype=int32)


#布尔类型张量，只需传入Python的布尔类型数据转换成tf内部布尔型即可 

In [16]:
a = tf.constant(True)
a

<tf.Tensor: id=22, shape=(), dtype=bool, numpy=True>

In [17]:
b = tf.constant([True,False])
b

<tf.Tensor: id=24, shape=(2,), dtype=bool, numpy=array([ True, False])>

# 类型转换（张量类型和精度）-利用tf.cast()

In [18]:
import numpy as np
a = tf.constant(np.pi,dtype=tf.float16)
tf.cast(a,tf.double)

<tf.Tensor: id=27, shape=(), dtype=float64, numpy=3.140625>

In [28]:
a = tf.constant([-1,0,1,2])
tf.cast(a,tf.bool)

<tf.Tensor: id=43, shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>

In [29]:
tf.cast(a,tf.bool).numpy()

array([ True, False,  True,  True])

# 待优化的张量-用tf.Variable类型表示

通过tf.Variable()函数可以将普通张量转化为待优化张量

In [30]:
a = tf.constant([-1.0,1,2])
aa = tf.Variable(a)
aa.name,aa.trainable

('Variable:0', True)

# 创建全0全1张量

In [32]:
tf.zeros([1]),tf.ones([1])

(<tf.Tensor: id=61, shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Tensor: id=64, shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>)

In [33]:
tf.zeros([2,2])

<tf.Tensor: id=69, shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

通过tf.zeros_like, tf.ones_like可以方便地新建与某个张量shape一致，内容全0或全1的张量。

In [36]:
a = tf.ones([2,3])
tf.zeros_like(a)

<tf.Tensor: id=84, shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

通过 tf.fill(shape, value)可以创建全为自定义数值 value 的张量。

In [37]:
tf.fill([2,3],-1)

<tf.Tensor: id=88, shape=(2, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]])>

# 创建已知分布的张量

通过 tf.random.normal(shape, mean=0.0, stddev=1.0)可以创建形状为 shape，均值为
mean，标准差为 stddev 的正态分布𝒩

In [38]:
tf.random.normal([2,2],0,1.0)

<tf.Tensor: id=95, shape=(2, 2), dtype=float32, numpy=
array([[-0.25906685,  0.8844525 ],
       [ 0.07207105, -0.5058348 ]], dtype=float32)>

通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自
[𝑚𝑖𝑛𝑣𝑎𝑙, 𝑚𝑎𝑥𝑣𝑎𝑙]区间的均匀分布的张量。

In [39]:
tf.random.uniform([2,2],maxval=10)

<tf.Tensor: id=103, shape=(2, 2), dtype=float32, numpy=
array([[1.4582515, 5.418273 ],
       [2.1414077, 2.3546135]], dtype=float32)>

# 创建序列

In [40]:
tf.range(10)

<tf.Tensor: id=108, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

通过 tf.range(start, limit, delta=1)可以创建[𝑠𝑡𝑎𝑟𝑡, 𝑙𝑖𝑚𝑖𝑡)，步长为 delta 的序列，不包含 limit
本身：

In [44]:
out = tf.random.uniform([4,10])
y = tf.constant([2,3,2,0])
y = tf.one_hot(y,depth=10)
loss = tf.keras.losses.mse(y,out)
loss = tf.reduce_mean(loss)
print(loss)

tf.Tensor(0.3532889, shape=(), dtype=float32)
