In [1]:
import tensorflow as tf
import numpy as np

In [3]:
dataset1 = tf.data.Dataset.range(5)
type(dataset1)

tensorflow.python.data.ops.dataset_ops.RangeDataset

In [4]:
for i in dataset1:
    print(i)
    print(i.numpy())

tf.Tensor(0, shape=(), dtype=int64)
0
tf.Tensor(1, shape=(), dtype=int64)
1
tf.Tensor(2, shape=(), dtype=int64)
2
tf.Tensor(3, shape=(), dtype=int64)
3
tf.Tensor(4, shape=(), dtype=int64)
4


In [5]:
def count(stop):
  i = 0
  while i<stop:
    print('第%s次调用……'%i)
    yield i
    i += 1

In [6]:
dataset2 = tf.data.Dataset.from_generator(count, args=[3], output_types=tf.int32, output_shapes = (),)

In [7]:
a = iter(dataset2)

In [8]:
next(a)

第0次调用……


<tf.Tensor: id=46, shape=(), dtype=int32, numpy=0>

In [9]:
next(a)

第1次调用……


<tf.Tensor: id=47, shape=(), dtype=int32, numpy=1>

In [10]:
'''通过接收其他类型的集合类对象创建Dataset对象。
这里所说的集合类型对象包含Python内置的list、tuple，numpy中的
ndarray等等。这种创建Dataset对象的方法大多通过from_tensors()和
from_tensor_slices()两个方法实现。'''

'通过接收其他类型的集合类对象创建Dataset对象。\n这里所说的集合类型对象包含Python内置的list、tuple，numpy中的\nndarray等等。这种创建Dataset对象的方法大多通过from_tensors()和\nfrom_tensor_slices()两个方法实现。'

In [11]:
a = [0,1,2,3,4]
dataset1 = tf.data.Dataset.from_tensors(a)
dataset1_n = tf.data.Dataset.from_tensors(np.array(a))
dataset1_t = tf.data.Dataset.from_tensors(tf.constant(a))

In [12]:
dataset1,next(iter(dataset1))

(<TensorDataset shapes: (5,), types: tf.int32>,
 <tf.Tensor: id=59, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>)

In [13]:
dataset1_n,next(iter(dataset1_n))

(<TensorDataset shapes: (5,), types: tf.int32>,
 <tf.Tensor: id=65, shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4])>)

In [16]:
dataset1_t,next(iter(dataset1_t)).numpy()

(<TensorDataset shapes: (5,), types: tf.int32>, array([0, 1, 2, 3, 4]))

In [17]:
a = [0,1,2,3,4]
b = [5,6,7,8,9]
dataset2 = tf.data.Dataset.from_tensors([a,b])
dataset2_n = tf.data.Dataset.from_tensors(np.array([a,b]))
dataset2_t = tf.data.Dataset.from_tensors(tf.constant([a,b]))

In [19]:
dataset2,next(iter(dataset2))

(<TensorDataset shapes: (2, 5), types: tf.int32>,
 <tf.Tensor: id=89, shape=(2, 5), dtype=int32, numpy=
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])>)

In [20]:
a = [0,1,2,3,4]
dataset1 = tf.data.Dataset.from_tensor_slices(a)

In [21]:
dataset1

<TensorSliceDataset shapes: (), types: tf.int32>

In [22]:
for i,elem in enumerate(dataset1):
    print(i, '-->', elem)

0 --> tf.Tensor(0, shape=(), dtype=int32)
1 --> tf.Tensor(1, shape=(), dtype=int32)
2 --> tf.Tensor(2, shape=(), dtype=int32)
3 --> tf.Tensor(3, shape=(), dtype=int32)
4 --> tf.Tensor(4, shape=(), dtype=int32)


In [23]:
a = [0,1,2,3,4]
b = [5,6,7,8,9]
dataset2 = tf.data.Dataset.from_tensor_slices([a,b])

In [24]:
dataset2

<TensorSliceDataset shapes: (5,), types: tf.int32>

In [25]:
for i,elem in enumerate(dataset2):
    print(i, '-->', elem)

0 --> tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
1 --> tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)


In [26]:
a = [0,1,2,3,4]
b = [5,6,7,8,9]
dataset1 = tf.data.Dataset.from_tensor_slices((a,b))

In [27]:
dataset1

<TensorSliceDataset shapes: ((), ()), types: (tf.int32, tf.int32)>

In [28]:
for i in dataset1:
    print(i)

(<tf.Tensor: id=119, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=120, shape=(), dtype=int32, numpy=5>)
(<tf.Tensor: id=121, shape=(), dtype=int32, numpy=1>, <tf.Tensor: id=122, shape=(), dtype=int32, numpy=6>)
(<tf.Tensor: id=123, shape=(), dtype=int32, numpy=2>, <tf.Tensor: id=124, shape=(), dtype=int32, numpy=7>)
(<tf.Tensor: id=125, shape=(), dtype=int32, numpy=3>, <tf.Tensor: id=126, shape=(), dtype=int32, numpy=8>)
(<tf.Tensor: id=127, shape=(), dtype=int32, numpy=4>, <tf.Tensor: id=128, shape=(), dtype=int32, numpy=9>)


In [29]:
c = ['a','b','c','d','e']
dataset3 = tf.data.Dataset.from_tensor_slices((a,b,c))

In [30]:
dataset3

<TensorSliceDataset shapes: ((), (), ()), types: (tf.int32, tf.int32, tf.string)>

In [33]:
for i in dataset3:
    print(i)

(<tf.Tensor: id=166, shape=(), dtype=int32, numpy=0>, <tf.Tensor: id=167, shape=(), dtype=int32, numpy=5>, <tf.Tensor: id=168, shape=(), dtype=string, numpy=b'a'>)
(<tf.Tensor: id=169, shape=(), dtype=int32, numpy=1>, <tf.Tensor: id=170, shape=(), dtype=int32, numpy=6>, <tf.Tensor: id=171, shape=(), dtype=string, numpy=b'b'>)
(<tf.Tensor: id=172, shape=(), dtype=int32, numpy=2>, <tf.Tensor: id=173, shape=(), dtype=int32, numpy=7>, <tf.Tensor: id=174, shape=(), dtype=string, numpy=b'c'>)
(<tf.Tensor: id=175, shape=(), dtype=int32, numpy=3>, <tf.Tensor: id=176, shape=(), dtype=int32, numpy=8>, <tf.Tensor: id=177, shape=(), dtype=string, numpy=b'd'>)
(<tf.Tensor: id=178, shape=(), dtype=int32, numpy=4>, <tf.Tensor: id=179, shape=(), dtype=int32, numpy=9>, <tf.Tensor: id=180, shape=(), dtype=string, numpy=b'e'>)
